logorotate: prevent missing file error
Previously, if pihole-FTL was never started, logrotate produced
the following output:
  error: stat of /var/log/pihole-FTL.log failed: No such file or directory

Such error was generating an annoying mail by cron.